# -*- coding: utf-8 -*-
"""Challenge 1 - Weather Agent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/qwiklabs-gcp-00-377e8e573e75/locations/us-central1/repositories/bf113203-b202-4f04-b2b1-10ceff2fcf1b
"""

!pip install requests==2.31.0
!pip install googlemaps==4.10.0

import requests

# Extract latitude and longitude from the geocode_result
# Assuming geocode_result is a list and contains a 'location' dictionary
if geocode_result and 'geometry' in geocode_result[0] and 'location' in geocode_result[0]['geometry']:
    lat = geocode_result[0]['geometry']['location']['lat']
    lon = geocode_result[0]['geometry']['location']['lng']
    print(f"Latitude: {lat}, Longitude: {lon}")

    # Construct the NWS API URL for points (metadata)
    nws_points_url = f"https://api.weather.gov/points/{lat},{lon}"
    print(f"NWS Points URL: {nws_points_url}")

    try:
        # Make the request to the NWS API
        headers = {'User-Agent': 'MyWeatherApp/1.0 (contact@example.com)'} # NWS API requires a User-Agent header
        response = requests.get(nws_points_url, headers=headers)
        response.raise_for_status()  # Raise an exception for HTTP errors

        # Parse the JSON response
        points_data = response.json()
        print("Successfully retrieved NWS points data.")
        #display(points_data) # You can uncomment this to see the full response

        # Extract the forecast URL from the points data
        forecast_url = points_data['properties']['forecast']
        print(f"NWS Forecast URL: {forecast_url}")

        # Now, make a request to the forecast URL
        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status() # Raise an exception for HTTP errors

        forecast_data = forecast_response.json()
        print("Successfully retrieved NWS forecast data.")
        display(forecast_data['properties']['periods'][0]) # Display the first period of the forecast

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong: {err}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
else:
    print("Could not extract latitude and longitude from geocode_result. Please ensure it's in the expected format.")

"""# Task
Get the weather forecast for a user-specified city by first geocoding the city name to latitude and longitude coordinates using the Google Maps Geocoding API, and then using these coordinates to fetch and display the forecast from the National Weather Service API.

## Get City Location

### Subtask:
Prompt the user to input the city for which they want to get the weather forecast.

**Reasoning**:
The subtask is to prompt the user for a city name. I will use a `code_block` to achieve this, using the `input()` function and storing the result in a variable named `city_name`.
"""

city_name = input("Enter the city name for weather forecast: ")
print(f"You entered: {city_name}")

"""# Task
Get the weather forecast for a user-specified city by first geocoding the city name to latitude and longitude coordinates using the Google Maps Geocoding API, and then using these coordinates to fetch and display the forecast from the National Weather Service API.

## Geocode Location - API Key Setup

### Subtask:
Provide instructions for the user to obtain and correctly set their Google Maps Platform API key. This will be presented as a markdown cell.

### Instructions to Obtain and Set Google Maps Platform API Key

To proceed with geocoding city names into geographical coordinates, you need a Google Maps Platform API key. Please follow these steps to obtain and configure your API key:

1.  **Go to the Google Cloud Console**: Open your web browser and navigate to [Google Cloud Console](https://console.cloud.google.com/).

2.  **Create or Select a Project**: If you don't have a project, create a new one. Otherwise, select an existing project from the dropdown menu at the top of the page.

3.  **Enable the Geocoding API**:
    *   In the Google Cloud Console, use the navigation menu (☰) on the left.
    *   Go to **APIs & Services > Library**.
    *   Search for "Geocoding API" and select it.
    *   Click the **Enable** button to enable the API for your selected project.

4.  **Create API Credentials (API Key)**:
    *   After enabling the API, go to **APIs & Services > Credentials** from the navigation menu.
    *   Click on **+ CREATE CREDENTIALS** at the top and select **API key**.
    *   A new API key will be generated and displayed. Copy this key.

5.  **Restrict Your API Key (Crucial for Security)**:
    *   **Do not use an unrestricted API key in production environments.**
    *   In the Credentials page, click on the API key you just created.
    *   Under "API restrictions", select **Restrict key**.
    *   Choose **Geocoding API** from the dropdown list to allow this key to only access the Geocoding API.
    *   Under "Application restrictions", you can restrict by HTTP referrers (websites), IP addresses, or Android/iOS apps. For this lab, if you are running it locally, you might restrict it to your IP address or leave it unrestricted for simplicity *during development only*. For web applications, restrict it to your domain.
    *   Click **Save**.

6.  **Replace the Placeholder**: Once you have your API key, replace `'YOUR_GOOGLE_API_KEY'` in the next code cell with the actual API key you just obtained.

This API key is essential for the upcoming geocoding step, which converts city names (like "Chicago") into precise geographical coordinates (latitude and longitude). Without it, the geocoding process will fail.

## Geocode Location - Execute Geocoding

### Subtask:
Use the `googlemaps` library with the provided API key to convert the `city_name` into latitude and longitude coordinates. The result will be stored in `geocode_result`.

**Reasoning**:
The subtask requires using the `googlemaps` library to geocode the `city_name` using the provided `G_API_KEY`. I will import the library, initialize the client, call the `geocode` method, store the result in `geocode_result`, and then print it for verification.
"""

import googlemaps

# Initialize the Google Maps client with your API key
gmaps = googlemaps.Client(key=G_API_KEY)

# Geocode the city name
geocode_result = gmaps.geocode(city_name)

# Print the geocoding result
print(geocode_result)

"""**Reasoning**:
The previous code failed because the `G_API_KEY` variable still contains a placeholder value, leading to a `ValueError: Invalid API key provided.`. I need to provide a new code cell for the user to set their actual Google API key.


"""

G_API_KEY = 'AIzaSyDiN5Y7loT7mL5GNJrnWHxICmcz9j0Vys4' # Replace 'YOUR_GOOGLE_API_KEY' with your actual API key
print("Please replace 'YOUR_GOOGLE_API_KEY' with your actual Google Maps Platform API key.")

"""**Reasoning**:
The user was just prompted to replace the placeholder API key with their actual Google Maps Platform API key. Now, I will re-attempt the geocoding step, expecting that the `G_API_KEY` variable has been correctly updated by the user.


"""

import googlemaps

# Initialize the Google Maps client with your API key
gmaps = googlemaps.Client(key=G_API_KEY)

# Geocode the city name
geocode_result = gmaps.geocode(city_name)

# Print the geocoding result
print(geocode_result)

"""## Fetch NWS Forecast

### Subtask:
Utilize the obtained latitude and longitude from the geocoded result to query the National Weather Service API for the weather forecast for that location.

**Reasoning**:
The subtask requires extracting latitude and longitude from the `geocode_result` and then using them to query the National Weather Service API for the weather forecast. This code block will perform the extraction, construct the NWS API URLs, make the necessary HTTP requests, handle potential errors, and display the forecast.
"""

import requests

# Extract latitude and longitude from the geocode_result
# Assuming geocode_result is a list and contains a 'location' dictionary
if geocode_result and 'geometry' in geocode_result[0] and 'location' in geocode_result[0]['geometry']:
    lat = geocode_result[0]['geometry']['location']['lat']
    lon = geocode_result[0]['geometry']['location']['lng']
    print(f"Latitude: {lat}, Longitude: {lon}")

    # Construct the NWS API URL for points (metadata)
    nws_points_url = f"https://api.weather.gov/points/{lat},{lon}"
    print(f"NWS Points URL: {nws_points_url}")

    try:
        # Make the request to the NWS API
        headers = {'User-Agent': 'MyWeatherApp/1.0 (contact@example.com)'} # NWS API requires a User-Agent header
        response = requests.get(nws_points_url, headers=headers)
        response.raise_for_status()  # Raise an exception for HTTP errors

        # Parse the JSON response
        points_data = response.json()
        print("Successfully retrieved NWS points data.")
        #display(points_data) # You can uncomment this to see the full response

        # Extract the forecast URL from the points data
        forecast_url = points_data['properties']['forecast']
        print(f"NWS Forecast URL: {forecast_url}")

        # Now, make a request to the forecast URL
        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status() # Raise an exception for HTTP errors

        forecast_data = forecast_response.json()
        print("Successfully retrieved NWS forecast data.")
        display(forecast_data['properties']['periods'][0]) # Display the first period of the forecast

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong: {err}")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
else:
    print("Could not extract latitude and longitude from geocode_result. Please ensure it's in the expected format.")

"""## Display Forecast

### Subtask:
Present the relevant weather forecast information retrieved from the National Weather Service API to the user.

**Reasoning**:
The subtask is to present the relevant weather forecast information from the `forecast_data` dictionary. I will iterate through the `periods` list within `forecast_data` and print the requested details for each period in a readable format, adding a separator between each period.
"""

print("--- Weather Forecast ---")
if 'properties' in forecast_data and 'periods' in forecast_data['properties']:
    for period in forecast_data['properties']['periods']:
        print(f"Period: {period['name']}")
        print(f"Temperature: {period['temperature']} {period['temperatureUnit']}")
        print(f"Short Forecast: {period['shortForecast']}")
        print(f"Detailed Forecast: {period['detailedForecast']}")
        print("------------------------")
else:
    print("Could not retrieve forecast periods from forecast_data.")

"""## Final Task

### Subtask:
Summarize the process and the weather forecast obtained.

## Summary:

### Data Analysis Key Findings

*   **API Key Setup:** Comprehensive instructions were successfully provided to guide users on obtaining and securing a Google Maps Platform API key, which is critical for geocoding.
*   **Geocoding Success:** The user-specified city name "chicagi" (intended as Chicago) was successfully geocoded using the Google Maps Geocoding API, yielding coordinates: latitude 41.88325 and longitude -87.6323879. The initial attempt correctly identified an invalid API key placeholder, necessitating user intervention.
*   **NWS Data Retrieval:** Using the geocoded coordinates, the National Weather Service (NWS) API was successfully queried.
    *   The NWS points API provided the specific forecast URL: `https://api.weather.gov/gridpoints/LOT/75,73/forecast`.
    *   The NWS forecast API was then successfully called, and weather data for the location was retrieved. For instance, the first period displayed a temperature of 40 F with a 'Sunny' short forecast.
*   **Forecast Display:** The retrieved weather forecast information, including period name, temperature, short forecast, and detailed forecast, was successfully extracted and presented for multiple periods (e.g., "Today", "Tonight", "Tuesday").

### Insights or Next Steps

*   The robust geocoding process can handle minor input variations (e.g., "chicagi" was correctly interpreted as Chicago), enhancing user experience.
*   Consider implementing a more user-friendly interface for city input and forecast display, and incorporate more advanced error handling for scenarios like API rate limits or non-existent city names.

# Task
Create a conversational weather forecast agent that prompts the user for a city name, uses the Google Maps Geocoding API (`https://maps.googleapis.com/maps/api/geocode/json`) to get its coordinates, and then fetches and displays the forecast from the National Weather Service API (`https://api.weather.gov/`) for those coordinates.

## Review and Consolidate Code

### Subtask:
Review the existing code for getting city input, geocoding with Google Maps, and fetching the National Weather Service forecast. Consolidate these steps into a clear, reusable structure for the agent.

### Code Review Summary

Based on the instructions, the existing code cells have been reviewed to identify the core functionalities and data flow:

1.  **City Input**: The `input()` function captures the `city_name` from the user.
2.  **API Key Setup**: The `G_API_KEY` variable is set to store the Google Maps Platform API key.
3.  **Geocoding**: The `googlemaps` library is used to initialize a client with `G_API_KEY` and then call `gmaps.geocode(city_name)` to produce `geocode_result`. From this, `lat` and `lon` are extracted.
4.  **NWS Points API**: The extracted `lat` and `lon` are used to construct `nws_points_url` (e.g., `https://api.weather.gov/points/{lat},{lon}`). A `requests.get()` call is made to this URL, and the `forecast_url` is extracted from the `points_data` response.
5.  **NWS Forecast API**: A subsequent `requests.get()` call is made to the `forecast_url`, retrieving the `forecast_data`.
6.  **Forecast Display**: The `forecast_data['properties']['periods']` is iterated through to display `name`, `temperature`, `temperatureUnit`, `shortForecast`, and `detailedForecast` for each period.

**Key Dependencies**: `requests` and `googlemaps` are used for API interactions.

This review confirms a clear linear flow from user input to final forecast display, involving two external API calls (Google Maps Geocoding and National Weather Service).

**Reasoning**:
The subtask is to consolidate the reviewed code into a reusable structure. I will create a Python function that encapsulates the entire weather forecast retrieval process, taking the city name and Google API key as arguments, thus making the logic reusable.
"""

def get_weather_forecast(city_name, google_api_key):
    """
    Fetches the weather forecast for a given city using Google Maps Geocoding
    and the National Weather Service API.

    Args:
        city_name (str): The name of the city to get the forecast for.
        google_api_key (str): Your Google Maps Platform API key.

    Returns:
        dict: The forecast data if successful, otherwise None.
    """
    import googlemaps
    import requests

    # 1. Geocode Location
    try:
        gmaps = googlemaps.Client(key=google_api_key)
        geocode_result = gmaps.geocode(city_name)

        if not geocode_result or 'geometry' not in geocode_result[0] or 'location' not in geocode_result[0]['geometry']:
            print(f"Error: Could not geocode city '{city_name}'.")
            return None

        lat = geocode_result[0]['geometry']['location']['lat']
        lon = geocode_result[0]['geometry']['location']['lng']
        print(f"Geocoded '{city_name}' to Latitude: {lat}, Longitude: {lon}")

    except ValueError as e:
        print(f"Error with Google API key or geocoding: {e}")
        return None
    except Exception as e:
        print(f"An unexpected error during geocoding: {e}")
        return None

    # 2. Fetch NWS Forecast
    nws_points_url = f"https://api.weather.gov/points/{lat},{lon}"
    headers = {'User-Agent': 'MyWeatherApp/1.0 (contact@example.com)'}

    try:
        response = requests.get(nws_points_url, headers=headers)
        response.raise_for_status()
        points_data = response.json()
        print("Successfully retrieved NWS points data.")

        forecast_url = points_data['properties']['forecast']
        print(f"NWS Forecast URL: {forecast_url}")

        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status()
        forecast_data = forecast_response.json()
        print("Successfully retrieved NWS forecast data.")

        # 3. Display Forecast
        print("\n--- Weather Forecast ---")
        if 'properties' in forecast_data and 'periods' in forecast_data['properties']:
            for period in forecast_data['properties']['periods']:
                print(f"Period: {period['name']}")
                print(f"Temperature: {period['temperature']} {period['temperatureUnit']}")
                print(f"Short Forecast: {period['shortForecast']}")
                print(f"Detailed Forecast: {period['detailedForecast']}")
                print("------------------------")
            return forecast_data
        else:
            print("Could not retrieve forecast periods from forecast_data.")
            return None

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error fetching NWS data: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting to NWS: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error fetching NWS: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong with NWS request: {err}")
    except Exception as e:
        print(f"An unexpected error occurred during NWS data retrieval or display: {e}")
    return None

print("A function 'get_weather_forecast' has been defined to consolidate the weather retrieval logic.")

"""## Implement Conversational Loop

### Subtask:
Create a Python script that implements a continuous conversational loop. This loop will prompt the user for input, process their request, and provide a response.

**Reasoning**:
I need to implement a continuous conversational loop as described in the instructions. This will involve a `while True` loop, user input, a check for an exit condition, and a confirmation message.
"""

while True:
    user_input = input("\nEnter a city name for the weather forecast or type 'exit' to quit: ")

    if user_input.lower() == 'exit':
        print("Exiting application. Goodbye!")
        break
    else:
        city_name = user_input
        print(f"You asked for the forecast for: {city_name}")

print("The conversational loop has ended.")

"""**Reasoning**:
Now that the conversational loop is established, I will integrate the `get_weather_forecast` function into the loop to fetch and display the weather for the user-entered city, using the `G_API_KEY`.


"""

print("\nHello! I'm Windy, your personal weather agent. I can fetch the current weather forecast for any city you'd like.\n")
print("Here are some ideas on how to use me:")
print("  - 'What's the weather in New York?'")
print("  - 'Forecast for London today.'")
print("  - 'How about the weather in Tokyo?'")
print("\nTo get started, simply type the name of a city. Type 'exit' to quit at any time.")

while True:
    user_input = input("\nEnter a city name for the weather forecast or type 'exit' to quit: ")

    if user_input.lower() == 'exit':
        print("Exiting application. Goodbye!")
        break
    else:
        city_name = user_input
        print(f"\nAgent: Retrieving weather forecast for {city_name}...")
        get_weather_forecast(city_name, G_API_KEY)

print("The conversational weather forecast agent has stopped.")

"""## Integrate Weather Logic

### Subtask:
Within the conversational loop, integrate the consolidated geocoding and NWS forecast logic. The agent should ask the user for a city, use the Google Maps API to get coordinates, and then fetch and display the weather forecast from the NWS API.

### Subtask: Integrate Weather Logic

Within the conversational loop, integrate the consolidated geocoding and NWS forecast logic. The agent should ask the user for a city, use the Google Maps API to get coordinates, and then fetch and display the weather forecast from the NWS API.

#### Instructions
1. Ensure you have replaced the placeholder value of `G_API_KEY` in a previous cell with your actual Google Maps Platform API key. Without a valid API key, the geocoding step will fail.
2. Run the code cell that contains the `while True:` loop and the call to the `get_weather_forecast` function. This will start the conversational weather agent.
3. When prompted, enter a city name (e.g., "New York", "London", "Tokyo") to see its weather forecast.
4. Observe the output, which should include the geocoded coordinates and the detailed weather forecast from the National Weather Service.
5. To exit the conversational loop, type 'exit' and press Enter.

## Final Task

### Subtask:
Summarize the process of converting the weather forecast code into a conversational agent.

## Summary:

### Q&A
The process successfully converted the weather forecast code into a conversational agent by first consolidating the core weather retrieval logic into a reusable function, then building a conversational loop, and finally integrating the weather logic into that loop.

### Data Analysis Key Findings

*   **Code Review and Consolidation:** The initial weather forecast logic, involving user input for city name, Google Maps Geocoding API for coordinates, and National Weather Service (NWS) API for forecast data, was thoroughly reviewed. This linear flow was then encapsulated into a single, reusable Python function named `get_weather_forecast(city_name, google_api_key)`, which includes robust error handling for both API interactions.
*   **Conversational Loop Implementation:** A continuous `while True:` loop was successfully implemented to serve as the conversational interface. This loop prompts the user for a city name, processes the input, and includes a graceful exit mechanism triggered by typing 'exit'.
*   **Integration of Weather Logic:** The consolidated `get_weather_forecast` function was successfully integrated into the conversational loop. The agent now asks the user for a city, uses the Google Maps API for geocoding, fetches the forecast from the NWS API, and displays the detailed weather information within the interactive session.
*   **User Guidance:** Clear instructions were provided for users on how to interact with the conversational agent, including inputting city names, understanding the output, and exiting the application. The importance of providing a valid Google Maps Platform API key (`G_API_KEY`) was also highlighted.

### Insights or Next Steps
*   The conversational weather agent is fully functional and ready for immediate use, provided a valid Google Maps Platform API key is configured.
*   Consider enhancing the agent with additional features, such as handling ambiguous city names, providing historical weather data, or allowing users to specify a forecast period (e.g., "tonight", "tomorrow").

# Task
Enhance the geocoding logic of the weather forecast agent to handle ambiguous city names by detecting if a city name yields multiple results from the Google Maps Geocoding API, and if so, prompt the user to specify the state to resolve the ambiguity before proceeding with the forecast.

## Enhance Geocoding for Ambiguous Cities

### Subtask:
Modify the geocoding logic to detect if a city name is ambiguous (i.e., exists in multiple states) and, if so, prompt the user to specify the state. Re-geocode with the specified state.

**Reasoning**:
The subtask is to modify the `get_weather_forecast` function to handle ambiguous city names by prompting the user for clarification if multiple geocoding results are found. I will update the existing `get_weather_forecast` function by adding logic to detect ambiguity, display options, solicit user input for clarification (either by selection number or state), and then re-geocode if necessary until an unambiguous result is obtained.
"""

def get_weather_forecast(city_name, google_api_key):
    """
    Fetches the weather forecast for a given city using Google Maps Geocoding
    and the National Weather Service API, with ambiguity resolution.

    Args:
        city_name (str): The name of the city to get the forecast for.
        google_api_key (str): Your Google Maps Platform API key.

    Returns:
        dict: The forecast data if successful, otherwise None.
    """
    import googlemaps
    import requests

    # 1. Geocode Location
    selected_geocode_result = None
    attempts = 0
    MAX_ATTEMPTS = 3 # Limit attempts to prevent infinite loops

    while selected_geocode_result is None and attempts < MAX_ATTEMPTS:
        try:
            gmaps = googlemaps.Client(key=google_api_key)
            current_geocode_city_name = city_name # Use a variable that can be updated for re-geocoding

            if attempts > 0: # If it's a retry, potentially with a state
                print(f"Retrying geocoding for '{current_geocode_city_name}'...")

            geocode_results = gmaps.geocode(current_geocode_city_name)

            if not geocode_results:
                print(f"Error: Could not geocode city '{current_geocode_city_name}'. Please try again.")
                return None

            if len(geocode_results) > 1:
                print(f"Multiple locations found for '{city_name}':")
                for i, result in enumerate(geocode_results):
                    print(f"{i+1}. {result['formatted_address']}")

                user_choice = input(
                    "Multiple locations found. Please specify the state (e.g., 'CA' for California) "
                    "or enter the number of your choice: "
                ).strip()

                if user_choice.isdigit():
                    choice_index = int(user_choice) - 1
                    if 0 <= choice_index < len(geocode_results):
                        selected_geocode_result = geocode_results[choice_index]
                        print(f"Selected: {selected_geocode_result['formatted_address']}")
                    else:
                        print("Invalid number. Please try again.")
                elif user_choice.isalpha() and len(user_choice) == 2: # Simple check for state abbreviation
                    city_name = f"{city_name}, {user_choice.upper()}" # Update city_name for re-geocoding
                    print(f"Attempting to re-geocode with '{city_name}'...")
                else:
                    print("Invalid input. Please enter a number or a 2-letter state abbreviation.")

            else: # Only one result, or unambiguous after re-geocoding
                selected_geocode_result = geocode_results[0]

        except ValueError as e:
            print(f"Error with Google API key or geocoding: {e}")
            return None
        except Exception as e:
            print(f"An unexpected error during geocoding: {e}")
            return None

        attempts += 1

    if selected_geocode_result is None:
        print("Could not resolve an unambiguous location after multiple attempts.")
        return None

    if 'geometry' not in selected_geocode_result or 'location' not in selected_geocode_result['geometry']:
        print(f"Error: Geocoding result for '{city_name}' did not contain geometry information.")
        return None

    lat = selected_geocode_result['geometry']['location']['lat']
    lon = selected_geocode_result['geometry']['location']['lng']
    print(f"Geocoded '{selected_geocode_result['formatted_address']}' to Latitude: {lat}, Longitude: {lon}")

    # 2. Fetch NWS Forecast
    nws_points_url = f"https://api.weather.gov/points/{lat},{lon}"
    headers = {'User-Agent': 'MyWeatherApp/1.0 (contact@example.com)'}

    try:
        response = requests.get(nws_points_url, headers=headers)
        response.raise_for_status()
        points_data = response.json()
        print("Successfully retrieved NWS points data.")

        forecast_url = points_data['properties']['forecast']
        print(f"NWS Forecast URL: {forecast_url}")

        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status()
        forecast_data = forecast_response.json()
        print("Successfully retrieved NWS forecast data.")

        # 3. Display Forecast
        print("\n--- Weather Forecast ---")
        if 'properties' in forecast_data and 'periods' in forecast_data['properties']:
            for period in forecast_data['properties']['periods']:
                print(f"Period: {period['name']}")
                print(f"Temperature: {period['temperature']} {period['temperatureUnit']}")
                print(f"Short Forecast: {period['shortForecast']}")
                print(f"Detailed Forecast: {period['detailedForecast']}")
                print("------------------------")
            return forecast_data
        else:
            print("Could not retrieve forecast periods from forecast_data.")
            return None

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error fetching NWS data: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting to NWS: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error fetching NWS: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong with NWS request: {err}")
    except Exception as e:
        print(f"An unexpected error occurred during NWS data retrieval or display: {e}")
    return None

print("The 'get_weather_forecast' function has been updated to handle ambiguous city names.")

"""## Integrate NWS Weather Alerts

### Subtask:
After successfully geocoding and fetching the forecast, make an additional API call to the National Weather Service (NWS) alerts endpoint. If any alerts are active for the given location, display them prominently to the user.

**Reasoning**:
The subtask requires modifying the `get_weather_forecast` function to include NWS weather alerts. I will update the existing function to make an additional API call to the NWS alerts endpoint after geocoding, parse the response, and display any active alerts or a message if none are found, along with appropriate error handling.
"""

def get_weather_forecast(city_name, google_api_key):
    """
    Fetches the weather forecast for a given city using Google Maps Geocoding
    and the National Weather Service API, with ambiguity resolution and weather alerts.

    Args:
        city_name (str): The name of the city to get the forecast for.
        google_api_key (str): Your Google Maps Platform API key.

    Returns:
        dict: The forecast data if successful, otherwise None.
    """
    import googlemaps
    import requests

    # 1. Geocode Location
    selected_geocode_result = None
    attempts = 0
    MAX_ATTEMPTS = 3 # Limit attempts to prevent infinite loops

    initial_city_name = city_name # Store the initial city name for display

    while selected_geocode_result is None and attempts < MAX_ATTEMPTS:
        try:
            gmaps = googlemaps.Client(key=google_api_key)
            current_geocode_city_name = city_name # Use a variable that can be updated for re-geocoding

            if attempts > 0: # If it's a retry, potentially with a state
                print(f"Retrying geocoding for '{current_geocode_city_name}'...")

            geocode_results = gmaps.geocode(current_geocode_city_name)

            if not geocode_results:
                print(f"Error: Could not geocode city '{current_geocode_city_name}'. Please try again.")
                return None

            if len(geocode_results) > 1:
                print(f"Multiple locations found for '{initial_city_name}':")
                for i, result in enumerate(geocode_results):
                    print(f"{i+1}. {result['formatted_address']}")

                user_choice = input(
                    "Multiple locations found. Please specify the state (e.g., 'CA' for California) "
                    "or enter the number of your choice: "
                ).strip()

                if user_choice.isdigit():
                    choice_index = int(user_choice) - 1
                    if 0 <= choice_index < len(geocode_results):
                        selected_geocode_result = geocode_results[choice_index]
                        print(f"Selected: {selected_geocode_result['formatted_address']}")
                    else:
                        print("Invalid number. Please try again.")
                elif user_choice.isalpha() and len(user_choice) == 2: # Simple check for state abbreviation
                    city_name = f"{initial_city_name}, {user_choice.upper()}" # Update city_name for re-geocoding, use initial_city_name
                    print(f"Attempting to re-geocode with '{city_name}'...")
                else:
                    print("Invalid input. Please enter a number or a 2-letter state abbreviation.")

            else: # Only one result, or unambiguous after re-geocoding
                selected_geocode_result = geocode_results[0]

        except ValueError as e:
            print(f"Error with Google API key or geocoding: {e}")
            return None
        except Exception as e:
            print(f"An unexpected error during geocoding: {e}")
            return None

        attempts += 1

    if selected_geocode_result is None:
        print("Could not resolve an unambiguous location after multiple attempts.")
        return None

    if 'geometry' not in selected_geocode_result or 'location' not in selected_geocode_result['geometry']:
        print(f"Error: Geocoding result for '{city_name}' did not contain geometry information.")
        return None

    lat = selected_geocode_result['geometry']['location']['lat']
    lon = selected_geocode_result['geometry']['location']['lng']
    print(f"Geocoded '{selected_geocode_result['formatted_address']}' to Latitude: {lat}, Longitude: {lon}")

    headers = {'User-Agent': 'MyWeatherApp/1.0 (contact@example.com)'}

    # 2. Fetch NWS Forecast
    nws_points_url = f"https://api.weather.gov/points/{lat},{lon}"
    forecast_data = None
    try:
        response = requests.get(nws_points_url, headers=headers)
        response.raise_for_status()
        points_data = response.json()
        print("Successfully retrieved NWS points data.")

        forecast_url = points_data['properties']['forecast']
        print(f"NWS Forecast URL: {forecast_url}")

        forecast_response = requests.get(forecast_url, headers=headers)
        forecast_response.raise_for_status()
        forecast_data = forecast_response.json()
        print("Successfully retrieved NWS forecast data.")

        # 3. Display Forecast
        print("\n--- Weather Forecast ---")
        if 'properties' in forecast_data and 'periods' in forecast_data['properties']:
            for period in forecast_data['properties']['periods']:
                print(f"Period: {period['name']}")
                print(f"Temperature: {period['temperature']} {period['temperatureUnit']}")
                print(f"Short Forecast: {period['shortForecast']}")
                print(f"Detailed Forecast: {period['detailedForecast']}")
                print("------------------------")
        else:
            print("Could not retrieve forecast periods from forecast_data.")

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error fetching NWS forecast data: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting to NWS forecast: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error fetching NWS forecast: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong with NWS forecast request: {err}")
    except Exception as e:
        print(f"An unexpected error occurred during NWS forecast retrieval or display: {e}")

    # 4. Fetch NWS Weather Alerts
    nws_alerts_url = f"https://api.weather.gov/alerts/active?point={lat},{lon}"
    print(f"NWS Alerts URL: {nws_alerts_url}")

    try:
        alerts_response = requests.get(nws_alerts_url, headers=headers)
        alerts_response.raise_for_status()
        alerts_data = alerts_response.json()
        print("Successfully retrieved NWS alerts data.")

        if 'features' in alerts_data and len(alerts_data['features']) > 0:
            print("\n--- ACTIVE WEATHER ALERTS ---")
            for alert in alerts_data['features']:
                properties = alert['properties']
                print(f"  EVENT: {properties.get('event', 'N/A')}")
                print(f"  SEVERITY: {properties.get('severity', 'N/A')}")
                print(f"  STATUS: {properties.get('status', 'N/A')}")
                print(f"  AREA: {properties.get('areaDesc', 'N/A')}")
                print(f"  DESCRIPTION: {properties.get('description', 'N/A')}")
                print("  -----------------------------")
            print("--- END ACTIVE WEATHER ALERTS ---")
        else:
            print("\nNo active weather alerts for this location.")

    except requests.exceptions.HTTPError as errh:
        print(f"Http Error fetching NWS alerts: {errh}")
    except requests.exceptions.ConnectionError as errc:
        print(f"Error Connecting to NWS alerts: {errc}")
    except requests.exceptions.Timeout as errt:
        print(f"Timeout Error fetching NWS alerts: {errt}")
    except requests.exceptions.RequestException as err:
        print(f"Something went wrong with NWS alerts request: {err}")
    except Exception as e:
        print(f"An unexpected error occurred during NWS alerts retrieval or display: {e}")

    return forecast_data

print("The 'get_weather_forecast' function has been updated to include weather alerts.")

"""## Update Conversational Flow

### Subtask:
Ensure the main conversational loop properly incorporates these new features, gracefully handling user input for ambiguous cities and presenting weather alerts.

#### Instructions
1. Run the code cell that initializes the conversational loop, which now includes the enhanced `get_weather_forecast` function.
2. When prompted, enter a city name. For ambiguous cities (e.g., 'Springfield'), observe how the agent prompts you to specify the state or select from a list.
3. After resolving any ambiguity, verify that the weather forecast and any active weather alerts (or a message indicating none) are displayed.
4. Test the 'exit' command to ensure the loop terminates correctly.

**Reasoning**:
I need to provide the code for the conversational loop which utilizes the updated `get_weather_forecast` function and the `G_API_KEY` to allow the user to interact with the weather agent, handling ambiguous city names and displaying alerts.
"""

print("\nHello! I'm Windy, your personal weather agent. I can fetch the current weather forecast for any city you'd like.\n")
print("Here are some ideas on how to use me:")
print("  - 'What's the weather in New York?'")
print("  - 'Forecast for London today.'")
print("  - 'How about the weather in Tokyo?'")
print("\nTo get started, simply type the name of a city. Type 'exit' to quit at any time.")

while True:
    user_input = input("\nEnter a city name for the weather forecast or type 'exit' to quit: ")

    if user_input.lower() == 'exit':
        print("Exiting application. Goodbye!")
        break
    else:
        city_name = user_input
        print(f"\nAgent: Retrieving weather forecast for {city_name}...")
        get_weather_forecast(city_name, G_API_KEY)

print("The conversational weather forecast agent has stopped.")

"""## Final Task

### Subtask:
Summarize the enhancements made to the conversational agent.

## Summary:

### Q&A
The conversational agent's geocoding logic has been successfully enhanced to handle ambiguous city names by prompting the user for state specification when multiple results are found. Additionally, the agent now integrates and displays active weather alerts from the National Weather Service. The main conversational flow has been updated to incorporate these new features, providing a more robust and informative user experience.

### Data Analysis Key Findings
*   The `get_weather_forecast` function was enhanced to detect ambiguous city names (multiple geocoding results). It prompts the user to specify a state (e.g., 'CA') or select from a numbered list, then re-geocodes with the clarified input. A `MAX_ATTEMPTS` mechanism (set to 3) is included to manage retries.
*   The `get_weather_forecast` function now integrates NWS weather alerts by making a separate API call to `https://api.weather.gov/alerts/active?point={lat},{lon}` after fetching the forecast.
*   If active alerts are found, the agent prominently displays details such as event, severity, status, area, and description. If no alerts are present, it informs the user.
*   Comprehensive error handling for API requests (HTTPError, ConnectionError, Timeout) was added for both forecast and alert fetching.
*   The main conversational loop successfully utilizes the enhanced `get_weather_forecast` function. When tested with "Chicago", it accurately geocoded the city, retrieved and displayed a 13-period weather forecast, and confirmed "No active weather alerts for this location."
*   The conversational flow also correctly processes an 'exit' command, terminating the application gracefully.

### Insights or Next Steps
*   The conversational agent now provides a more user-friendly and comprehensive weather service by actively resolving ambiguous city inputs and delivering crucial weather alerts. This significantly improves reliability and user satisfaction.
*   Further enhancements could include supporting more complex natural language queries, integrating historical weather data, or providing weather maps for a richer user experience.
"""